task:
  name: segmentation
  output_dir_name: segmentation
  batch_size: 16
  max_epochs: 32
  max_steps: null
  target_metric: val_mIoU
  target_metric_mode: max
  model:
    name: nvidia/mit-b0
    use_pretrained_model: false  # just to compare performance, use this with 'engine.test_only=true'
    contiguous_memory: true  # silences pytorch warnings but increases memory footprint
engine:
  devices: 4
  sbatch_args:
    time: 05:00:00
optimizer:
  name: adamw_baseline
evaluation:
  plot:
    metric: test_mIoU
    test_metric_mode: max
    format: "0.2"
    limits: [30, 38]
