task:
  name: graph_tiny
  output_dir_name: graph_tiny
  batch_size: 1
  max_epochs: 50
  max_steps: null
  target_metric: val_acc
  target_metric_mode: max
  dataset_split: public  # public, full, geom-gcn, random
  model:  # GCN
    hidden_channels: 64
    num_layers: 2
    dropout: 0.5
    cached: False
    normalize: True
    reset_params: False
engine:
  devices: 1
  sbatch_args:
    time: 00:05:00
optimizer:
  name: adamw_baseline
  learning_rate: 1.0e-1
  weight_decay: 1.0e-3
evaluation:
  plot:
    metric: test_acc
    test_metric_mode: max
    format: "2.2"
    limits: [70, 85]
