optimizer:
  name: template             # same as folder name
  output_dir_name: template  # if you want a different name for the output folder, defaults to optimizer name if removed
  learning_rate: 1.e-3
